version: '3'
services:
    nginx:
        image: nginx:1.12
        ports:
            - "80:80"
        volumes:
            - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf
            - ./:/var/www/html # NGINX also needs access to serve statics
    composer:
        image: composer/composer
        volumes:
            - .:/app
        command: install
    php:
        container_name: local_php71
        image: maelstromeous/docker:php-71-xdebug
        volumes:
          - ./:/var/www/html
        ports:
          - "1337:9000"
    mysql:
        image: mysql:5.7
        container_name: local_mysql
        volumes:
            - deadpoolvol:/var/mysql/data
        environment:
            MYSQL_ROOT_PASSWORD: root
        ports:
            - "3306:3306"
volumes:
    deadpoolvol:
        external: true