AppBundle\Entity\Quote:
    type: entity
    table: quotes
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    fields:
        quote:
            type: text
        added:
            type: datetime